"""empty message

Revision ID: 2ad444b4fc8d
Revises: 306776eb4527
Create Date: 2020-08-17 17:58:09.216473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad444b4fc8d'
down_revision = '306776eb4527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_user_email_key', 'user', type_='unique')
    op.drop_constraint('user_user_mobile_key', 'user', type_='unique')
    op.drop_constraint('user_user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_user_name_key', 'user', ['user_name'])
    op.create_unique_constraint('user_user_mobile_key', 'user', ['user_mobile'])
    op.create_unique_constraint('user_user_email_key', 'user', ['user_email'])
    # ### end Alembic commands ###
