"""empty message

Revision ID: 306776eb4527
Revises: 
Create Date: 2020-08-11 19:59:39.147824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306776eb4527'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=True),
    sa.Column('role_desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=2000), nullable=True),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('user_address', sa.String(length=200), nullable=True),
    sa.Column('user_mobile', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_mobile'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('blog',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('blog_title', sa.String(length=120), nullable=True),
    sa.Column('blog_type', sa.String(length=120), nullable=True),
    sa.Column('blog_desc', sa.Text(), nullable=True),
    sa.Column('blog_content', sa.Text(), nullable=True),
    sa.Column('blog_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('blog_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
