"""empty message

Revision ID: 4cf06a63a03f
Revises: 2ad444b4fc8d
Create Date: 2020-08-18 02:23:58.376457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf06a63a03f'
down_revision = '2ad444b4fc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'blog_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('blog', 'blog_desc',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('blog', 'blog_title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('blog', 'blog_type',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('user', 'user_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('user', 'user_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'user_mobile',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user', 'user_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'user_mobile',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'user_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'user_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('blog', 'blog_type',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('blog', 'blog_title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('blog', 'blog_desc',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('blog', 'blog_content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
